### ISSUE TITLE
How can i connect to the WLAN-VPN-Pi after reboot?

### ISSUE THREAD

**Issue by NoTrace-Kai** [martinsauter/WLAN-VPN-Pi#14]
Hi there ...
is there any option to get ob the pi with ssh after i rebooted it?
I know this:
"IMPORTANT: After the reboot it's not possible anymore to ssh into the Raspi via the Ethernet interface for security reasons (as this interface is now backhaul and there should be no SSH access from the backhaul). Therefore you MUST use the Wi-Fi "Pi_AP" to connect!"
But can i get a connect to the Pi when i am connected over wlan to the VPN-Pi?
Thanks for a little help ...
CU Kai

**Comment by martinsauter** [comment]
Hm, not quite sure I understand your question. But perhaps this will help: After the configuration you can access the Pi via SSH over the Wifi Access point connection. If you want to connect from the Ethernet port, edit /etc/ssh/ssdh_conf and remove the line 8: 'ListenAddress 192.168.55.1'. Without that line you can login from all network interfaces again.

**Comment by NoTrace-Kai** [comment]
Yes. 
I installed the raspberry with your script and after the reboot I did not get on my raspberry again. 
Not over the IP address in my network and not over the IP address from the new network. 
I got the IP 192.168.55.10 on my notebook. 
Then I will start another try and will edit the ash_conf file befor I do a reboot. 
Thanks a lot.

**Comment by NoTrace-Kai** [comment]
Now i removed- line 8: 'ListenAddress 192.168.55.1' -
and i can connect to the Pi again ... Thanks for your help.
