### ISSUE TITLE
No Wifi Network

### ISSUE THREAD

**Issue by hamzux** [martinsauter/WLAN-VPN-Pi#4]
Hello,

I ran the install script and it went ok. After rebooting, I saw no wifi network called Pi_AP. 

I tried to connect as hidden network but no success.

Env: Raspberry Pi model B with raspbian Jessie Lite

Thank you

**Comment by martinsauter** [comment]
Perhaps the hostapd executable wasn't installed correctly or you don't have a compatible Wi-Fi dongle!? I only tried with the one described in the "iki. To debug I suggest the following:

1. Insert the Pi's SD card in your computer as at the moment you probably don't have access to that configuration at all as the Wifi is not working.

2. Change the SSHD configuration so ssh is available over eth0 again (it's blocked for security reasons) so yo can log into the system over Ethernet again.

3. Boot the Pi again. 

4. Once you can log into the system via eth0 the next step is to look at the script that was executed to create the WLAN-VPN-Pi. There is a section that downloads the hostapd executable that works with the Wi-Fi dongle I used. Have a look how that is done and then see if the backup files that were created are there and if a hostapd is there. If it is there, then it's probably an incompatible dongle. If the hostapd executable is missing manually repeat the steps to download it as per the script.

5. I noticed that you used a "Jessie Lite" build. When I last tried there was only a standard "Jessie" build available. perhaps that also makes a difference?

**Comment by martinsauter** [comment]
Ran a test with Jessie Lite and things are working as expected. Therefore closing the issue.

**Comment by hamzux** [comment]
Thank you for your response. 

It turned out that the hostapd version I used was not suitable for the wifi dongle I have. 

It's now working as expected. 

Regards

**Comment by martinsauter** [comment]
Did you buy a compatible Wifi USB dongle or are you using a different hostapd now? If it is the later I'd be interested in the combination you use!
