### ISSUE TITLE
How to deal with captive portal?

### ISSUE THREAD

**Issue by dbadia** [martinsauter/WLAN-VPN-Pi#5]
Great work on this, just built one of these before my last business trip.  Had tested it here at home and everything was working great.  However, once at the hotel they had a captive portal which apparently stopped my ras pi from connecting to the VPN.  

I connected directly to the hotel network from my laptop, and it looks like the hotels captive portal set a browser cookie once you accepted the ToC, etc.  I even tried connecting via my laptop -> ras pi (vpn off) -> hotel network in the hopes that it would just grant access to my ras pis IP, but no luck, the connection attempts to my VPN still failed.  Also, each device had to go through the portal and accept the ToC again.

Due to that, I was never able to get my VPN to start on the ras pi.  Curious if anyone else has had this issue and if there are any known solutions?

If this is the wrong place to ask, please let me know.

Thanks
Dave

**Comment by martinsauter** [comment]
Hm, if you can access the Internet after you've done your thing on the portal but the VPN tunnel (that otherwise works) won't come up then they are blocking VPNs. Shame on the hotel. Which one and where is it?

**Comment by dbadia** [comment]
Hyatt Regency in New Orleans
Disappointed that a hotel that hosts so many conferences would do that

**Comment by martinsauter** [comment]
Indeed, thanks for the info!
