### ISSUE TITLE
WIFI could not connect

### ISSUE THREAD

**Issue by cars10wi** [martinsauter/WLAN-VPN-Pi#6]
Moin Moin,
ich versuche seit zwei Tagen, leider vergeblich, einen AP zu erzeugen.
Ich habe hier einen RasPi2 mit 2 EDIMAX EW7811U Sticks.
Als Grundsystem habe ich die aktuelle Raspian minimal Version installiert.
Das Script läuft auch sauber durch.
Nach einem Neustart bekomme ich den AP auch angezeigt, wenn ich mich verbinden möchte bricht er dabei aber immer ab (OSX und Android). Leider haben alle Tutorials das selbe Ergebnis geliefert.
Vielleicht hast du noch eine Idee?

mfg 
Carsten

**Comment by martinsauter** [comment]
Hm, ich nehme mal an der EW7811U und EW7811UN sind das Gleiche? 

Am Raspian Mini auf Jessie Basis kann es eigentlich nicht liegen, das habe ich auch schon gemacht. Das Passwort hast Du richtig eingegeben? (siehe hostapd.conf).

Du könntest mal schauen ob auf dem Raspi in /var/log/syslog ein Eintrag über Wifi Verbindungsversuche vorhanden ist. Falls Du nicht auf das System kommst weil Wifi nicht geht, kannst Du die SD Karte auch in den PC einlegen und dann von dort aus die Log Datei anschauen.

**Comment by martinsauter** [comment]
Da sollte in etwa so aussehen:

`
Jun 26 08:40:30 my-pi hostapd: wlan0: STA 12:34:56:78:90:11 IEEE 802.11: associated

Jun 26 08:40:30 my-pi hostapd: wlan0: STA 12:34:56:78:90:11 RADIUS: starting accounting session FFFFFFF-0000000D

Jun 26 08:40:30 my-pi hostapd: wlan0: STA 12:34:56:78:90:11 WPA: pairwise key handshake completed (RSN)

Jun 26 08:40:30 my-pi dhcpd: DHCPDISCOVER from 12:34:56:78:90:11 (android-xxxxx) via wlan0

Jun 26 08:40:31 my-pi dhcpd: DHCPOFFER on 192.168.44.30 to 12:34:56:78:90:11 (android-bef645ffd15cd1f) via wlan0

Jun 26 08:40:31 my-pi dhcpd: DHCPREQUEST for 192.168.44.30 (192.168.57.1) from 12:34:56:78:90:11 (android-bef645ffd15cxxxxxd1f) via wlan0

Jun 26 08:40:31 my-pi dhcpd: DHCPACK on 192.168.44.30 to 12:34:56:78:90:11 via wlan0
`

**Comment by cars10wi** [comment]
Ich hab hier auch den EW7811UN.
Ich lass grad das Script noch einmal auf einer jungfräulichen Installation durchlaufen. Danach werde ich die Logs testen.  Vielen Dank schon einmal für die schnelle Hilfe.

**Comment by cars10wi** [comment]
Hmm es scheint ein problem mit der hostapd zu geben:

Jun 28 19:02:13 raspberrypi systemd[1]: hostapd.service: control process exited, code=killed status=9
Jun 28 19:02:13 raspberrypi systemd[1]: Failed to start LSB: Advanced IEEE 802.11 management daemon.
Jun 28 19:02:13 raspberrypi systemd[1]: Unit hostapd.service entered failed state.
Jun 28 19:02:13 raspberrypi dhcpd: Internet Systems Consortium DHCP Server 4.3.1
Jun 28 19:02:13 raspberrypi dhcpd: Copyright 2004-2014 Internet Systems Consortium.
Jun 28 19:02:13 raspberrypi dhcpd: All rights reserved.
Jun 28 19:02:13 raspberrypi dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Jun 28 19:02:14 raspberrypi dhcpd: Internet Systems Consortium DHCP Server 4.3.1
Jun 28 19:02:14 raspberrypi dhcpd: Copyright 2004-2014 Internet Systems Consortium.
Jun 28 19:02:14 raspberrypi dhcpd: All rights reserved.
Jun 28 19:02:14 raspberrypi dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Jun 28 19:02:14 raspberrypi dhcpd: Wrote 0 leases to leases file.
Jun 28 19:02:14 raspberrypi ntpd[777]: Listen normally on 2 lo 127.0.0.1 UDP 123
Jun 28 19:02:14 raspberrypi ntpd[777]: Listen normally on 3 eth0 192.168.1.30 UDP 123
Jun 28 19:02:14 raspberrypi ntpd[777]: Listen normally on 4 wlan0 192.168.55.1 UDP 123
Jun 28 19:02:14 raspberrypi ntpd[777]: peers refreshed
Jun 28 19:02:14 raspberrypi ntpd[777]: Listening on routing socket on fd #21 for interface updates
Jun 28 19:02:14 raspberrypi hostapd[755]: Starting advanced IEEE 802.11 management: hosted

[syslog.txt](https://github.com/martinsauter/WLAN-VPN-Pi/files/337873/syslog.txt)

**Comment by cars10wi** [comment]
Moin Moin. 
Ich bin jetzt einen Schritt weiter. Wenn ich die Verschlüsselung in der hostapd komplett auskommentiere kann ich mich connecten. 
Solbald ich die # wieder entferne geht es wieder nicht.

**Comment by martinsauter** [comment]
Aha!? Sehr seltsam, noch nie gesehen... :-(

**Comment by martinsauter** [comment]
mach mal ein 'sudo lsusb' auf dem Raspberry Pi, vielleicht stimmt was mit dem Wifi USB stick nicht!?

**Comment by cars10wi** [comment]
Servus,
ich hab den Fehler gefunden:
mit dem dpi-update wurde der Kernel: 4.4.14-v7+ installiert. Der erzeugt diese Fehler.
Ich hab jetzt erst einmal den 3.8.16 installiert. Damit läuft der AP, ich kann mich mit Kennwort connecten und es gibt eine IP.
Danke für die Hilfe und vielleicht hilft diese Info anderen Betroffenen.

**Comment by martinsauter** [comment]
Urgh, das ist aber nicht gut :-( Gibt es da eine einfach Möglichkeit einen älteren Kernel wieder einzuspielen? Ich werde das am Wochenende auch mal ausprobieren... Danke für die Info!

**Comment by cars10wi** [comment]
Ich habs nach der (http://www.forum-raspberrypi.de/Thread-tutorial-firmware-u-kernel-downgrade-mit-rpi-update) Anleitung gemacht.

**Comment by martinsauter** [comment]
Super, danke, da bin ich ja mal gespannt! Aktuelle habe ich auf meinem Client Linux 4.1.20-v7+ #867 von 23. März 2016 laufen. Wäre echt arg wenn der Kernel das kaputt macht...

**Comment by martinsauter** [comment]
I just upgraded from kernel 4.1 to 4.4 and the problem occurs on my Pi as well. As a quick stop gap I'll comment out the rpi-update in the installation script until I've found a solution for new kernels!

**Comment by martinsauter** [comment]
Downloaded the latest rtl hostapd sources, recompiled and installed in /usr/sbin. No luck, still not working. Downgrading the kernel to 3.18 as per the link above and things are working again. That does not bode well... :-(
