### ISSUE TITLE
Custom hostapd , wlan0 and Raspberry Pi 3

### ISSUE THREAD

**Issue by echaritos** [martinsauter/WLAN-VPN-Pi#8]
A big thank you for all your work writing this script. 
I think it makes more sense for the Raspberry Pi 3 to have hostapd set on the onboard WiFi (`wlan0`). That way you don't need the custom `hostapd `in your script. This makes sense when you want only to bridge `eth0 `to `wlan0`. You don't need a dongle. 
In case you want to bridge `wlan1 `(Edimax EW-7811UN) with `wlan0 `you don't need the custom `hostapd`. 
I have build a client VPN and WiFi AP with Raspberry Pi 3, Edimax EW-7811UN using the native `hostapd `and it works just fine. 
Just for your consideration.
Thank you.

**Comment by martinsauter** [comment]
This is really good news as last time I checked, newer kernels break the functionality of the alternative hostapd required for the Edimax dongle. Not sure if this has changed again, will give it a try again this week. I've also ordered a Pi 3 just now so I can modify + test the script to alternatively use the default hostapd + built-in Wifi. I'll do that once the hardware arrives and will then update the script and Wiki descriptions. I'll keep you posted here.

**Comment by echaritos** [comment]
Thanks. I am interested on your updates. 
I think using the proposed configuration (native `hostapd` on the onboard `wlan0`) on the Raspberry Pi 3 is important since any non-vanilla software on a security application will always raise some eyebrows

**Comment by martinsauter** [comment]
I've included most of your changes of the pull request but have done it in a slightly different way. Have a look. Thanks for the work, very much appreciated!!!
